version = 0.1
[default.deploy.parameters]
stack_name = "task-manager-spring"
resolve_s3 = true
s3_prefix = "task-manager-spring"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["TaskManagerFunction=668933070809.dkr.ecr.ap-southeast-1.amazonaws.com/taskmanagerspringcc268896/taskmanagerfunctionbb077d9arepo"]
