name: Build and deploy frontend

on:
  workflow_dispatch:

env:
  AWS_REGION: ap-southeast-1
  ROLE_TO_ASSUME: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/TaskManager-GithubAction-Role

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies
        run: cd client && npm install

      - name: Build
        run: cd client && npm run build

      - name: Copy to S3
        run: aws s3 cp client/build {{ vars.S3_BUCKET_URL }} --recursive
